#!/bin/bash

## ant2img is a simple bash script that automates drawing graphs from Apache
## Ant's build.xml.  To perform such thing, this script invokes a XSLT using
## xalan and then feeds the result to graphviz's dot.
##
## The XSLT used is ant2dot.xsl [0] which does not belong to this project
## This script also requires the xalan.jar to work
##
## [0] http://ant2dot.sourceforge.net/

THIS_NAME=$(basename $0)
THIS_VERSION='2012-05-17'

. /etc/${THIS_NAME}.conf

usage() {
  echo "${THIS_NAME} v${THIS_VERSION}"
  echo -e "\nUsage:"
  echo -e "\t${THIS_NAME} [FILENAME]"
}

if [ -z ${1} ]; then
  echo "No file specified. Assuming './build.xml'"
  build_xml='build.xml'
else
  build_xml=${1}
fi

if [ ! -f ${build_xml} ]; then
  echo 'No input file found. Please specify an Ant build file.'
  exit 1
fi

file_base=${build_xml/.xml/}
outfile_dot=${file_base}.dot

output_img_format='png'
if [ -n "${OUTPUT_IMG_FORMAT}" ]; then
  output_img_format=${OUTPUT_IMG_FORMAT}
fi

java -cp ${XALAN_JAR} \
    org.apache.xalan.xslt.Process \
    -XSL ${ANT2DOT_XSLT} \
    -IN ${build_xml} \
    -OUT ${outfile_dot} \
    ${ANT2DOT_OPTIONS}

dot -T${output_img_format} ${outfile_dot} -o ${file_base}.${output_img_format}

if [ -n "${EXEC_AFTER}" ]; then
  eval ${EXEC_AFTER}
fi
